# Generated by Django 5.2 on 2025-04-27 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=255)),
                ('patient_id', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('unassigned', 'Unassigned'), ('assigned', 'Assigned')], default='unassigned', max_length=20)),
                ('physician', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('unassigned', 'Unassigned'), ('assigned', 'Assigned'), ('reported', 'Reported')], default='unassigned', max_length=20)),
                ('patient_id', models.CharField(max_length=64, unique=True)),
                ('patient_name', models.CharField(max_length=200)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('modality', models.CharField(choices=[('MR', 'MR'), ('CT', 'CT'), ('Other', 'Other')], max_length=10)),
                ('study_type', models.CharField(max_length=100)),
                ('receiving_date', models.DateField()),
                ('number_of_images', models.PositiveIntegerField(default=0)),
                ('report_submitted', models.BooleanField(default=False)),
                ('report_file', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('study_date', models.DateField(blank=True, null=True)),
                ('report_time', models.DateTimeField(blank=True, null=True)),
                ('institution_name', models.CharField(max_length=200)),
                ('preferred_physician', models.ForeignKey(blank=True, limit_choices_to={'role': 'doctor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DicomFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='dicom_files/')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portals.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portals.patient')),
            ],
        ),
    ]
